class TopicsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  def topics
    topic_array = [
      "Food",
      "Recipes",
      "DIY",
      "Home",
      "Parenting",
      "Health",
      "Fitness",
      "Wellness",
      "Yoga",
      "Meditation",
      "Travel",
      "Adventure",
      "Culture",
      "Languages",
      "Technology",
      "Coding",
      "WebDev",
      "MachineLearning",
      "Blockchain",
      "Design",
      "UX/UI",
      "Photography",
      "Art",
      "Illustration",
      "Music",
      "Movies",
      "Books",
      "Writing",
      "Poetry",
      "Fiction",
      "Science",
      "Space",
      "Environment",
      "Nature",
      "Animals",
      "History",
      "Education",
      "Psychology",
      "Philosophy",
      "Society",
      "Politics",
      "Business",
      "Entrepreneurship",
      "Finance",
      "Investing",
      "Marketing",
      "Productivity",
      "SelfImprovement",
      "Relationships",
      "Lifestyle",
      "Fashion",
      "Beauty",
      "Sports",
      "Gaming",
      "Coding"
    ]

    render json: topic_array
  end
end
